"""create health data domain

Revision ID: 0311597601c8
Revises:
Create Date: 2026-08-29 21:11:37.548017
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0311597601c8"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exam_items",
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("radiation", sa.Boolean(), server_default="0", nullable=False),
        sa.Column(
            "cost_level",
            sa.Enum(
                "low",
                "medium",
                "high",
                name="cost_level",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("recommended_interval_months", sa.Integer(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "recommended_interval_months IS NULL OR recommended_interval_months > 0",
            name=op.f("ck_exam_items_interval_positive"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exam_items")),
    )
    op.create_index(op.f("ix_exam_items_category"), "exam_items", ["category"], unique=False)
    op.create_index(op.f("ix_exam_items_code"), "exam_items", ["code"], unique=True)
    op.create_table(
        "metric_dictionaries",
        sa.Column("metric_code", sa.String(length=64), nullable=False),
        sa.Column("canonical_name", sa.String(length=200), nullable=False),
        sa.Column("aliases", sa.JSON(), nullable=False),
        sa.Column("standard_unit", sa.String(length=50), nullable=True),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("unit_conversions", sa.JSON(), nullable=False),
        sa.Column("valid_min", sa.Float(), nullable=True),
        sa.Column("valid_max", sa.Float(), nullable=True),
        sa.Column("source", sa.String(length=200), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "valid_min IS NULL OR valid_max IS NULL OR valid_min <= valid_max",
            name=op.f("ck_metric_dictionaries_valid_range_order"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_metric_dictionaries")),
    )
    op.create_index(
        op.f("ix_metric_dictionaries_category"), "metric_dictionaries", ["category"], unique=False
    )
    op.create_index(
        op.f("ix_metric_dictionaries_metric_code"),
        "metric_dictionaries",
        ["metric_code"],
        unique=True,
    )
    op.create_table(
        "patients",
        sa.Column("anonymous_code", sa.String(length=64), nullable=False),
        sa.Column(
            "gender",
            sa.Enum(
                "female",
                "male",
                "other",
                "unknown",
                name="gender",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column("height", sa.Float(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "height IS NULL OR (height > 0 AND height <= 300)",
            name=op.f("ck_patients_height_range"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_patients")),
    )
    op.create_index(op.f("ix_patients_anonymous_code"), "patients", ["anonymous_code"], unique=True)
    op.create_table(
        "health_checks",
        sa.Column("patient_id", sa.String(length=36), nullable=False),
        sa.Column("check_date", sa.Date(), nullable=False),
        sa.Column("institution", sa.String(length=200), nullable=True),
        sa.Column("is_demo", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
            name=op.f("fk_health_checks_patient_id_patients"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_health_checks")),
    )
    op.create_index(
        op.f("ix_health_checks_check_date"), "health_checks", ["check_date"], unique=False
    )
    op.create_index(op.f("ix_health_checks_is_demo"), "health_checks", ["is_demo"], unique=False)
    op.create_index(
        "ix_health_checks_patient_date", "health_checks", ["patient_id", "check_date"], unique=False
    )
    op.create_index(
        op.f("ix_health_checks_patient_id"), "health_checks", ["patient_id"], unique=False
    )
    op.create_table(
        "lesion_tracks",
        sa.Column("patient_id", sa.String(length=36), nullable=False),
        sa.Column("canonical_lesion_id", sa.String(length=100), nullable=False),
        sa.Column("lesion_type", sa.String(length=100), nullable=False),
        sa.Column("location", sa.String(length=100), nullable=False),
        sa.Column("first_seen", sa.Date(), nullable=False),
        sa.Column("last_seen", sa.Date(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("first_seen <= last_seen", name=op.f("ck_lesion_tracks_date_order")),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
            name=op.f("fk_lesion_tracks_patient_id_patients"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lesion_tracks")),
    )
    op.create_index(
        op.f("ix_lesion_tracks_canonical_lesion_id"),
        "lesion_tracks",
        ["canonical_lesion_id"],
        unique=True,
    )
    op.create_index(op.f("ix_lesion_tracks_location"), "lesion_tracks", ["location"], unique=False)
    op.create_index(
        op.f("ix_lesion_tracks_patient_id"), "lesion_tracks", ["patient_id"], unique=False
    )
    op.create_index(
        "ix_lesion_tracks_patient_type",
        "lesion_tracks",
        ["patient_id", "lesion_type"],
        unique=False,
    )
    op.create_table(
        "medical_rules",
        sa.Column("rule_code", sa.String(length=100), nullable=False),
        sa.Column("rule_type", sa.String(length=100), nullable=False),
        sa.Column("exam_item_id", sa.String(length=36), nullable=True),
        sa.Column("condition_json", sa.JSON(), nullable=False),
        sa.Column(
            "action",
            sa.Enum(
                "include",
                "exclude",
                "adjust_score",
                "require_review",
                name="rule_action",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=300), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default="1", nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("priority >= 0", name=op.f("ck_medical_rules_priority_nonnegative")),
        sa.ForeignKeyConstraint(
            ["exam_item_id"],
            ["exam_items.id"],
            name=op.f("fk_medical_rules_exam_item_id_exam_items"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_medical_rules")),
        sa.UniqueConstraint("rule_code", "version", name="uq_medical_rule_code_version"),
    )
    op.create_index(op.f("ix_medical_rules_enabled"), "medical_rules", ["enabled"], unique=False)
    op.create_index(
        op.f("ix_medical_rules_exam_item_id"), "medical_rules", ["exam_item_id"], unique=False
    )
    op.create_index(
        op.f("ix_medical_rules_rule_code"), "medical_rules", ["rule_code"], unique=False
    )
    op.create_index(
        op.f("ix_medical_rules_rule_type"), "medical_rules", ["rule_type"], unique=False
    )
    op.create_table(
        "exam_histories",
        sa.Column("health_check_id", sa.String(length=36), nullable=False),
        sa.Column("exam_item_id", sa.String(length=36), nullable=False),
        sa.Column(
            "result_status",
            sa.Enum(
                "completed",
                "normal",
                "abnormal",
                "inconclusive",
                "unknown",
                name="exam_result_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["exam_item_id"],
            ["exam_items.id"],
            name=op.f("fk_exam_histories_exam_item_id_exam_items"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["health_check_id"],
            ["health_checks.id"],
            name=op.f("fk_exam_histories_health_check_id_health_checks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exam_histories")),
        sa.UniqueConstraint("health_check_id", "exam_item_id", name="uq_exam_history_check_item"),
    )
    op.create_index(
        op.f("ix_exam_histories_exam_item_id"), "exam_histories", ["exam_item_id"], unique=False
    )
    op.create_index(
        op.f("ix_exam_histories_health_check_id"),
        "exam_histories",
        ["health_check_id"],
        unique=False,
    )
    op.create_table(
        "imaging_exams",
        sa.Column("health_check_id", sa.String(length=36), nullable=False),
        sa.Column("exam_type", sa.String(length=100), nullable=False),
        sa.Column("body_part", sa.String(length=100), nullable=False),
        sa.Column("report_text", sa.Text(), nullable=True),
        sa.Column("exam_date", sa.Date(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["health_check_id"],
            ["health_checks.id"],
            name=op.f("fk_imaging_exams_health_check_id_health_checks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_imaging_exams")),
    )
    op.create_index(
        op.f("ix_imaging_exams_body_part"), "imaging_exams", ["body_part"], unique=False
    )
    op.create_index(
        "ix_imaging_exams_check_date",
        "imaging_exams",
        ["health_check_id", "exam_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_imaging_exams_exam_type"), "imaging_exams", ["exam_type"], unique=False
    )
    op.create_index(
        op.f("ix_imaging_exams_health_check_id"), "imaging_exams", ["health_check_id"], unique=False
    )
    op.create_table(
        "lab_metrics",
        sa.Column("health_check_id", sa.String(length=36), nullable=False),
        sa.Column("metric_code", sa.String(length=64), nullable=False),
        sa.Column("original_name", sa.String(length=200), nullable=False),
        sa.Column("canonical_name", sa.String(length=200), nullable=False),
        sa.Column("original_value", sa.String(length=100), nullable=False),
        sa.Column("value", sa.Float(), nullable=True),
        sa.Column("original_unit", sa.String(length=50), nullable=True),
        sa.Column("standard_unit", sa.String(length=50), nullable=True),
        sa.Column("reference_min", sa.Float(), nullable=True),
        sa.Column("reference_max", sa.Float(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "normal",
                "low",
                "high",
                "unknown",
                name="metric_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "normalization_status",
            sa.Enum(
                "normalized",
                "unmapped_metric",
                "invalid_value",
                "unsupported_unit",
                "implausible_value",
                "invalid_reference",
                name="normalization_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("normalization_version", sa.String(length=64), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "reference_min IS NULL OR reference_max IS NULL OR reference_min <= reference_max",
            name=op.f("ck_lab_metrics_reference_range_order"),
        ),
        sa.ForeignKeyConstraint(
            ["health_check_id"],
            ["health_checks.id"],
            name=op.f("fk_lab_metrics_health_check_id_health_checks"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["metric_code"],
            ["metric_dictionaries.metric_code"],
            name=op.f("fk_lab_metrics_metric_code_metric_dictionaries"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lab_metrics")),
    )
    op.create_index(
        "ix_lab_metrics_check_code", "lab_metrics", ["health_check_id", "metric_code"], unique=False
    )
    op.create_index(
        op.f("ix_lab_metrics_health_check_id"), "lab_metrics", ["health_check_id"], unique=False
    )
    op.create_index(
        op.f("ix_lab_metrics_metric_code"), "lab_metrics", ["metric_code"], unique=False
    )
    op.create_table(
        "recommendations",
        sa.Column("patient_id", sa.String(length=36), nullable=False),
        sa.Column("as_of_health_check_id", sa.String(length=36), nullable=True),
        sa.Column(
            "plan_tier",
            sa.Enum(
                "simplified",
                "standard",
                "deep",
                name="plan_tier",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "review",
                "confirmed",
                name="recommendation_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("feature_pipeline_version", sa.String(length=64), nullable=True),
        sa.Column("risk_model_version", sa.String(length=64), nullable=True),
        sa.Column("recommendation_model_version", sa.String(length=64), nullable=True),
        sa.Column("rule_version", sa.String(length=64), nullable=True),
        sa.Column("trace_id", sa.String(length=100), nullable=False),
        sa.Column("is_demo", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["as_of_health_check_id"],
            ["health_checks.id"],
            name=op.f("fk_recommendations_as_of_health_check_id_health_checks"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
            name=op.f("fk_recommendations_patient_id_patients"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recommendations")),
    )
    op.create_index(
        op.f("ix_recommendations_patient_id"), "recommendations", ["patient_id"], unique=False
    )
    op.create_index(
        op.f("ix_recommendations_trace_id"), "recommendations", ["trace_id"], unique=False
    )
    op.create_table(
        "risk_predictions",
        sa.Column("patient_id", sa.String(length=36), nullable=False),
        sa.Column("as_of_health_check_id", sa.String(length=36), nullable=True),
        sa.Column("risk_code", sa.String(length=100), nullable=False),
        sa.Column("probability", sa.Float(), nullable=False),
        sa.Column("risk_level", sa.String(length=50), nullable=True),
        sa.Column("feature_pipeline_version", sa.String(length=64), nullable=False),
        sa.Column("risk_model_version", sa.String(length=64), nullable=False),
        sa.Column("evidence_refs", sa.JSON(), nullable=False),
        sa.Column("trace_id", sa.String(length=100), nullable=False),
        sa.Column("is_demo", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "probability >= 0 AND probability <= 1",
            name=op.f("ck_risk_predictions_probability_range"),
        ),
        sa.ForeignKeyConstraint(
            ["as_of_health_check_id"],
            ["health_checks.id"],
            name=op.f("fk_risk_predictions_as_of_health_check_id_health_checks"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
            name=op.f("fk_risk_predictions_patient_id_patients"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_risk_predictions")),
    )
    op.create_index(
        "ix_risk_predictions_patient_code",
        "risk_predictions",
        ["patient_id", "risk_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_risk_predictions_patient_id"), "risk_predictions", ["patient_id"], unique=False
    )
    op.create_index(
        op.f("ix_risk_predictions_risk_code"), "risk_predictions", ["risk_code"], unique=False
    )
    op.create_index(
        op.f("ix_risk_predictions_trace_id"), "risk_predictions", ["trace_id"], unique=False
    )
    op.create_table(
        "ai_reports",
        sa.Column("patient_id", sa.String(length=36), nullable=False),
        sa.Column("recommendation_id", sa.String(length=36), nullable=True),
        sa.Column(
            "report_type",
            sa.Enum(
                "health_summary",
                "recommendation_explanation",
                "chat_summary",
                name="ai_report_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("llm_model", sa.String(length=100), nullable=False),
        sa.Column("prompt_version", sa.String(length=64), nullable=False),
        sa.Column("source_trace_id", sa.String(length=100), nullable=False),
        sa.Column("is_demo", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
            name=op.f("fk_ai_reports_patient_id_patients"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["recommendation_id"],
            ["recommendations.id"],
            name=op.f("fk_ai_reports_recommendation_id_recommendations"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_reports")),
    )
    op.create_index(op.f("ix_ai_reports_patient_id"), "ai_reports", ["patient_id"], unique=False)
    op.create_index(
        op.f("ix_ai_reports_recommendation_id"), "ai_reports", ["recommendation_id"], unique=False
    )
    op.create_index(
        op.f("ix_ai_reports_source_trace_id"), "ai_reports", ["source_trace_id"], unique=False
    )
    op.create_table(
        "lesions",
        sa.Column("imaging_exam_id", sa.String(length=36), nullable=False),
        sa.Column("lesion_type", sa.String(length=100), nullable=False),
        sa.Column("original_location", sa.String(length=200), nullable=False),
        sa.Column("location", sa.String(length=100), nullable=False),
        sa.Column("size_mm", sa.Float(), nullable=True),
        sa.Column("grade", sa.String(length=100), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "size_mm IS NULL OR size_mm >= 0", name=op.f("ck_lesions_size_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["imaging_exam_id"],
            ["imaging_exams.id"],
            name=op.f("fk_lesions_imaging_exam_id_imaging_exams"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lesions")),
    )
    op.create_index(
        op.f("ix_lesions_imaging_exam_id"), "lesions", ["imaging_exam_id"], unique=False
    )
    op.create_index(op.f("ix_lesions_lesion_type"), "lesions", ["lesion_type"], unique=False)
    op.create_index(op.f("ix_lesions_location"), "lesions", ["location"], unique=False)
    op.create_table(
        "recommendation_items",
        sa.Column("recommendation_id", sa.String(length=36), nullable=False),
        sa.Column("exam_item_id", sa.String(length=36), nullable=False),
        sa.Column("model_score", sa.Float(), nullable=True),
        sa.Column("final_score", sa.Float(), nullable=True),
        sa.Column(
            "decision",
            sa.Enum(
                "include",
                "exclude",
                "require_review",
                name="recommendation_decision",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("rank", sa.Integer(), nullable=True),
        sa.Column("explanation", sa.Text(), nullable=True),
        sa.Column("evidence_refs", sa.JSON(), nullable=False),
        sa.Column("applied_rules", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "final_score IS NULL OR (final_score >= 0 AND final_score <= 1)",
            name=op.f("ck_recommendation_items_final_score_range"),
        ),
        sa.CheckConstraint(
            "model_score IS NULL OR (model_score >= 0 AND model_score <= 1)",
            name=op.f("ck_recommendation_items_model_score_range"),
        ),
        sa.CheckConstraint(
            "rank IS NULL OR rank > 0", name=op.f("ck_recommendation_items_rank_positive")
        ),
        sa.ForeignKeyConstraint(
            ["exam_item_id"],
            ["exam_items.id"],
            name=op.f("fk_recommendation_items_exam_item_id_exam_items"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["recommendation_id"],
            ["recommendations.id"],
            name=op.f("fk_recommendation_items_recommendation_id_recommendations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recommendation_items")),
        sa.UniqueConstraint(
            "recommendation_id", "exam_item_id", name="uq_recommendation_item_exam_item"
        ),
    )
    op.create_index(
        op.f("ix_recommendation_items_exam_item_id"),
        "recommendation_items",
        ["exam_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recommendation_items_recommendation_id"),
        "recommendation_items",
        ["recommendation_id"],
        unique=False,
    )
    op.create_table(
        "lesion_observations",
        sa.Column("lesion_track_id", sa.String(length=36), nullable=False),
        sa.Column("lesion_id", sa.String(length=36), nullable=False),
        sa.Column("exam_date", sa.Date(), nullable=False),
        sa.Column("size_mm", sa.Float(), nullable=True),
        sa.Column("grade", sa.String(length=100), nullable=True),
        sa.Column("match_confidence", sa.Float(), nullable=False),
        sa.Column(
            "match_status",
            sa.Enum(
                "candidate",
                "manual_confirmed",
                "rejected",
                "unmatched",
                name="match_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "match_confidence >= 0 AND match_confidence <= 1",
            name=op.f("ck_lesion_observations_confidence_range"),
        ),
        sa.CheckConstraint(
            "size_mm IS NULL OR size_mm >= 0", name=op.f("ck_lesion_observations_size_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["lesion_id"],
            ["lesions.id"],
            name=op.f("fk_lesion_observations_lesion_id_lesions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["lesion_track_id"],
            ["lesion_tracks.id"],
            name=op.f("fk_lesion_observations_lesion_track_id_lesion_tracks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lesion_observations")),
    )
    op.create_index(
        op.f("ix_lesion_observations_lesion_id"), "lesion_observations", ["lesion_id"], unique=True
    )
    op.create_index(
        op.f("ix_lesion_observations_lesion_track_id"),
        "lesion_observations",
        ["lesion_track_id"],
        unique=False,
    )
    op.create_index(
        "ix_lesion_observations_track_date",
        "lesion_observations",
        ["lesion_track_id", "exam_date"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_lesion_observations_track_date", table_name="lesion_observations")
    op.drop_index(op.f("ix_lesion_observations_lesion_track_id"), table_name="lesion_observations")
    op.drop_index(op.f("ix_lesion_observations_lesion_id"), table_name="lesion_observations")
    op.drop_table("lesion_observations")
    op.drop_index(
        op.f("ix_recommendation_items_recommendation_id"), table_name="recommendation_items"
    )
    op.drop_index(op.f("ix_recommendation_items_exam_item_id"), table_name="recommendation_items")
    op.drop_table("recommendation_items")
    op.drop_index(op.f("ix_lesions_location"), table_name="lesions")
    op.drop_index(op.f("ix_lesions_lesion_type"), table_name="lesions")
    op.drop_index(op.f("ix_lesions_imaging_exam_id"), table_name="lesions")
    op.drop_table("lesions")
    op.drop_index(op.f("ix_ai_reports_source_trace_id"), table_name="ai_reports")
    op.drop_index(op.f("ix_ai_reports_recommendation_id"), table_name="ai_reports")
    op.drop_index(op.f("ix_ai_reports_patient_id"), table_name="ai_reports")
    op.drop_table("ai_reports")
    op.drop_index(op.f("ix_risk_predictions_trace_id"), table_name="risk_predictions")
    op.drop_index(op.f("ix_risk_predictions_risk_code"), table_name="risk_predictions")
    op.drop_index(op.f("ix_risk_predictions_patient_id"), table_name="risk_predictions")
    op.drop_index("ix_risk_predictions_patient_code", table_name="risk_predictions")
    op.drop_table("risk_predictions")
    op.drop_index(op.f("ix_recommendations_trace_id"), table_name="recommendations")
    op.drop_index(op.f("ix_recommendations_patient_id"), table_name="recommendations")
    op.drop_table("recommendations")
    op.drop_index(op.f("ix_lab_metrics_metric_code"), table_name="lab_metrics")
    op.drop_index(op.f("ix_lab_metrics_health_check_id"), table_name="lab_metrics")
    op.drop_index("ix_lab_metrics_check_code", table_name="lab_metrics")
    op.drop_table("lab_metrics")
    op.drop_index(op.f("ix_imaging_exams_health_check_id"), table_name="imaging_exams")
    op.drop_index(op.f("ix_imaging_exams_exam_type"), table_name="imaging_exams")
    op.drop_index("ix_imaging_exams_check_date", table_name="imaging_exams")
    op.drop_index(op.f("ix_imaging_exams_body_part"), table_name="imaging_exams")
    op.drop_table("imaging_exams")
    op.drop_index(op.f("ix_exam_histories_health_check_id"), table_name="exam_histories")
    op.drop_index(op.f("ix_exam_histories_exam_item_id"), table_name="exam_histories")
    op.drop_table("exam_histories")
    op.drop_index(op.f("ix_medical_rules_rule_type"), table_name="medical_rules")
    op.drop_index(op.f("ix_medical_rules_rule_code"), table_name="medical_rules")
    op.drop_index(op.f("ix_medical_rules_exam_item_id"), table_name="medical_rules")
    op.drop_index(op.f("ix_medical_rules_enabled"), table_name="medical_rules")
    op.drop_table("medical_rules")
    op.drop_index("ix_lesion_tracks_patient_type", table_name="lesion_tracks")
    op.drop_index(op.f("ix_lesion_tracks_patient_id"), table_name="lesion_tracks")
    op.drop_index(op.f("ix_lesion_tracks_location"), table_name="lesion_tracks")
    op.drop_index(op.f("ix_lesion_tracks_canonical_lesion_id"), table_name="lesion_tracks")
    op.drop_table("lesion_tracks")
    op.drop_index(op.f("ix_health_checks_patient_id"), table_name="health_checks")
    op.drop_index("ix_health_checks_patient_date", table_name="health_checks")
    op.drop_index(op.f("ix_health_checks_is_demo"), table_name="health_checks")
    op.drop_index(op.f("ix_health_checks_check_date"), table_name="health_checks")
    op.drop_table("health_checks")
    op.drop_index(op.f("ix_patients_anonymous_code"), table_name="patients")
    op.drop_table("patients")
    op.drop_index(op.f("ix_metric_dictionaries_metric_code"), table_name="metric_dictionaries")
    op.drop_index(op.f("ix_metric_dictionaries_category"), table_name="metric_dictionaries")
    op.drop_table("metric_dictionaries")
    op.drop_index(op.f("ix_exam_items_code"), table_name="exam_items")
    op.drop_index(op.f("ix_exam_items_category"), table_name="exam_items")
    op.drop_table("exam_items")
    # ### end Alembic commands ###
